name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  targetFile: # id of input
    description: 'Who to greet'
    required: true
    default: 'ctfe.pub'
  targetBaseUrl: # id of input
    description: 'Who to greet'
    required: true
    default: 'https://sigstore-tuf-root.storage.googleapis.com/targets'
  metadataBaseUrl: # id of input
    description: 'Who to greet'
    required: true
    default: 'https://sigstore-tuf-root.storage.googleapis.com'
  rootMetadataUrl:
    description: 'Who to greet'
    required: true
    default: 'https://sigstore-tuf-root.storage.googleapis.com/1.root.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
