name: 'TUF Client Fetch Target'
description: 'This is a Github Action to test the tuf-js client'
inputs:
  target-file:
    description: 'the taget file to fetch'
    required: true
  root-metadata-url:
    description: 'the first version of root metadata'
    required: true
  metadata-base-url:
    description: 'the base url which contains all metadata'
    required: true
  target-base-url:
    description: 'the base url which contains the target file to fetch'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
